### ISSUE TITLE
`rhino::build_js` not working

### ISSUE THREAD

**Issue by pietrodito** [Appsilon/rhino#498]
### Steps to reproduce

1. Following the [tutorial](https://appsilon.github.io/rhino/articles/tutorial/create-your-first-rhino-app.htm)
2. Everything works fine till the step `rhino::build_js()`

### Bug description

 rhino::build_js()

> build-js
> webpack

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find package '@babel/preset-react' imported from /home/rstudio/Apps/RhinoApp/.rhino/babel-virtual-resolve-base.js
    at new NodeError (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
    at packageResolve (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
    at moduleResolve (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:902:20)
    at defaultResolve (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:985:15)
    at resolve (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:999:12)
    at tryImportMetaResolve (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/files/plugins.js:137:45)
    at resolveStandardizedNameForImport (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/files/plugins.js:159:19)
    at resolveStandardizedName (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/files/plugins.js:168:12)
    at loadPreset (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/files/plugins.js:56:20)
    at loadPreset.next (<anonymous>)
    at createDescriptor (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:291:5)
    at /home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:43:15)
    at Function.all (/home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPresetDescriptors (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-descriptors.js:96:17)
    at createPresetDescriptors.next (<anonymous>)
    at /home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/gensync-utils/functional.js:21:23
    at Generator.next (<anonymous>)
    at mergeChainOpts (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-chain.js:351:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-chain.js:317:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-chain.js:192:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/config-chain.js:78:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadPartialConfig (/home/rstudio/Apps/RhinoApp/node_modules/@babel/core/lib/config/partial.js:115:25)
    at loadPartialConfig.next (<anonymous>)
    at step (/home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:269:25)
    at /home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:223:11)
    at /home/rstudio/Apps/RhinoApp/node_modules/gensync/index.js:37:40 {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.18.0
Error in `npm_raw()`:
! System command 'npm' exited with status 1.
Run `rlang::last_trace()` to see where the error occurred.

### Expected behavior

No error

### Rhino diagnostics

Linux 6.5.3-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Sep 13 12:21:35 UTC 2023
R version 4.3.1 (2023-06-16)
rhino: 1.5.0
node: v18.18.0

### Comments

Keep on the good work!

**Comment by pietrodito** [comment]
cannot reproduce this on fresh install.
